import type { OandaInstrument } from '@/lib/types/oanda'

/**
 * Static instrument definitions for Coinbase crypto pairs.
 * Matches OandaInstrument shape so TradeOrderForm works without changes.
 */
export const COINBASE_INSTRUMENTS: OandaInstrument[] = [
    {
        name: 'CRYPTO_BTC_USD',
        displayName: 'BTC/USD',
        type: 'CRYPTO',
        pipLocation: -2,
        displayPrecision: 2,
        tradeUnitsPrecision: 8,
        minimumTradeSize: '0.00001',
        maximumTrailingStopDistance: '50000',
        minimumTrailingStopDistance: '10',
        maximumPositionSize: '100',
        maximumOrderUnits: '100',
        marginRate: '1',
    },
    {
        name: 'CRYPTO_ETH_USD',
        displayName: 'ETH/USD',
        type: 'CRYPTO',
        pipLocation: -2,
        displayPrecision: 2,
        tradeUnitsPrecision: 8,
        minimumTradeSize: '0.0001',
        maximumTrailingStopDistance: '10000',
        minimumTrailingStopDistance: '1',
        maximumPositionSize: '1000',
        maximumOrderUnits: '1000',
        marginRate: '1',
    },
    {
        name: 'CRYPTO_SOL_USD',
        displayName: 'SOL/USD',
        type: 'CRYPTO',
        pipLocation: -2,
        displayPrecision: 2,
        tradeUnitsPrecision: 6,
        minimumTradeSize: '0.01',
        maximumTrailingStopDistance: '1000',
        minimumTrailingStopDistance: '0.1',
        maximumPositionSize: '10000',
        maximumOrderUnits: '10000',
        marginRate: '1',
    },
    {
        name: 'CRYPTO_XRP_USD',
        displayName: 'XRP/USD',
        type: 'CRYPTO',
        pipLocation: -4,
        displayPrecision: 4,
        tradeUnitsPrecision: 2,
        minimumTradeSize: '1',
        maximumTrailingStopDistance: '100',
        minimumTrailingStopDistance: '0.01',
        maximumPositionSize: '1000000',
        maximumOrderUnits: '1000000',
        marginRate: '1',
    },
    {
        name: 'CRYPTO_DOGE_USD',
        displayName: 'DOGE/USD',
        type: 'CRYPTO',
        pipLocation: -5,
        displayPrecision: 5,
        tradeUnitsPrecision: 0,
        minimumTradeSize: '1',
        maximumTrailingStopDistance: '10',
        minimumTrailingStopDistance: '0.001',
        maximumPositionSize: '10000000',
        maximumOrderUnits: '10000000',
        marginRate: '1',
    },
    {
        name: 'CRYPTO_ADA_USD',
        displayName: 'ADA/USD',
        type: 'CRYPTO',
        pipLocation: -4,
        displayPrecision: 4,
        tradeUnitsPrecision: 2,
        minimumTradeSize: '1',
        maximumTrailingStopDistance: '100',
        minimumTrailingStopDistance: '0.01',
        maximumPositionSize: '1000000',
        maximumOrderUnits: '1000000',
        marginRate: '1',
    },
    {
        name: 'CRYPTO_BNB_USD',
        displayName: 'BNB/USD',
        type: 'CRYPTO',
        pipLocation: -2,
        displayPrecision: 2,
        tradeUnitsPrecision: 5,
        minimumTradeSize: '0.001',
        maximumTrailingStopDistance: '5000',
        minimumTrailingStopDistance: '0.5',
        maximumPositionSize: '10000',
        maximumOrderUnits: '10000',
        marginRate: '1',
    },
    {
        name: 'CRYPTO_AVAX_USD',
        displayName: 'AVAX/USD',
        type: 'CRYPTO',
        pipLocation: -2,
        displayPrecision: 2,
        tradeUnitsPrecision: 4,
        minimumTradeSize: '0.01',
        maximumTrailingStopDistance: '1000',
        minimumTrailingStopDistance: '0.1',
        maximumPositionSize: '100000',
        maximumOrderUnits: '100000',
        marginRate: '1',
    },
    {
        name: 'CRYPTO_DOT_USD',
        displayName: 'DOT/USD',
        type: 'CRYPTO',
        pipLocation: -3,
        displayPrecision: 3,
        tradeUnitsPrecision: 3,
        minimumTradeSize: '0.1',
        maximumTrailingStopDistance: '500',
        minimumTrailingStopDistance: '0.05',
        maximumPositionSize: '500000',
        maximumOrderUnits: '500000',
        marginRate: '1',
    },
    {
        name: 'CRYPTO_MATIC_USD',
        displayName: 'POL/USD',
        type: 'CRYPTO',
        pipLocation: -4,
        displayPrecision: 4,
        tradeUnitsPrecision: 2,
        minimumTradeSize: '1',
        maximumTrailingStopDistance: '100',
        minimumTrailingStopDistance: '0.01',
        maximumPositionSize: '5000000',
        maximumOrderUnits: '5000000',
        marginRate: '1',
    },
]
