import type { OandaInstrument } from '@/lib/types/oanda'

/**
 * Kraken Crypto Instruments
 * Map these to OandaInstrument shape so the UI/TradeOrderForm can use them without changes.
 */
export const KRAKEN_INSTRUMENTS: OandaInstrument[] = [
    {
        name: 'CRYPTO_BTC_USD',
        type: 'CRYPTO',
        displayName: 'BTC/USD',
        pipLocation: -1,
        displayPrecision: 1,
        tradeUnitsPrecision: 8,
        minimumTradeSize: '0.0001',
        maximumTrailingStopDistance: '100000',
        minimumTrailingStopDistance: '1',
        maximumPositionSize: '1000',
        maximumOrderUnits: '1000',
        marginRate: '0.02',
        financing: { longRate: '0.02', shortRate: '0.02', financingDaysOfWeek: [] }
    },
    {
        name: 'CRYPTO_ETH_USD',
        type: 'CRYPTO',
        displayName: 'ETH/USD',
        pipLocation: -2,
        displayPrecision: 2,
        tradeUnitsPrecision: 8,
        minimumTradeSize: '0.001',
        maximumTrailingStopDistance: '100000',
        minimumTrailingStopDistance: '1',
        maximumPositionSize: '1000',
        maximumOrderUnits: '1000',
        marginRate: '0.02',
        financing: { longRate: '0.02', shortRate: '0.02', financingDaysOfWeek: [] }
    },
    {
        name: 'CRYPTO_SOL_USD',
        type: 'CRYPTO',
        displayName: 'SOL/USD',
        pipLocation: -2,
        displayPrecision: 2,
        tradeUnitsPrecision: 4,
        minimumTradeSize: '0.01',
        maximumTrailingStopDistance: '100000',
        minimumTrailingStopDistance: '1',
        maximumPositionSize: '1000',
        maximumOrderUnits: '1000',
        marginRate: '0.02',
        financing: { longRate: '0.02', shortRate: '0.02', financingDaysOfWeek: [] }
    },
    {
        name: 'CRYPTO_XRP_USD',
        type: 'CRYPTO',
        displayName: 'XRP/USD',
        pipLocation: -5,
        displayPrecision: 5,
        tradeUnitsPrecision: 1,
        minimumTradeSize: '1',
        maximumTrailingStopDistance: '100000',
        minimumTrailingStopDistance: '1',
        maximumPositionSize: '1000',
        maximumOrderUnits: '1000',
        marginRate: '0.02',
        financing: { longRate: '0.02', shortRate: '0.02', financingDaysOfWeek: [] }
    },
    {
        name: 'CRYPTO_DOGE_USD',
        type: 'CRYPTO',
        displayName: 'DOGE/USD',
        pipLocation: -5,
        displayPrecision: 5,
        tradeUnitsPrecision: 0,
        minimumTradeSize: '10',
        maximumTrailingStopDistance: '100000',
        minimumTrailingStopDistance: '1',
        maximumPositionSize: '1000',
        maximumOrderUnits: '1000',
        marginRate: '0.02',
        financing: { longRate: '0.02', shortRate: '0.02', financingDaysOfWeek: [] }
    },
    {
        name: 'CRYPTO_ADA_USD',
        type: 'CRYPTO',
        displayName: 'ADA/USD',
        pipLocation: -4,
        displayPrecision: 4,
        tradeUnitsPrecision: 1,
        minimumTradeSize: '1',
        maximumTrailingStopDistance: '100000',
        minimumTrailingStopDistance: '1',
        maximumPositionSize: '1000',
        maximumOrderUnits: '1000',
        marginRate: '0.02',
        financing: { longRate: '0.02', shortRate: '0.02', financingDaysOfWeek: [] }
    },
    {
        name: 'CRYPTO_BNB_USD',
        type: 'CRYPTO',
        displayName: 'BNB/USD',
        pipLocation: -2,
        displayPrecision: 2,
        tradeUnitsPrecision: 3,
        minimumTradeSize: '0.01',
        maximumTrailingStopDistance: '100000',
        minimumTrailingStopDistance: '1',
        maximumPositionSize: '1000',
        maximumOrderUnits: '1000',
        marginRate: '0.02',
        financing: { longRate: '0.02', shortRate: '0.02', financingDaysOfWeek: [] }
    },
    {
        name: 'CRYPTO_AVAX_USD',
        type: 'CRYPTO',
        displayName: 'AVAX/USD',
        pipLocation: -2,
        displayPrecision: 2,
        tradeUnitsPrecision: 3,
        minimumTradeSize: '0.01',
        maximumTrailingStopDistance: '100000',
        minimumTrailingStopDistance: '1',
        maximumPositionSize: '1000',
        maximumOrderUnits: '1000',
        marginRate: '0.02',
        financing: { longRate: '0.02', shortRate: '0.02', financingDaysOfWeek: [] }
    },
    {
        name: 'CRYPTO_DOT_USD',
        type: 'CRYPTO',
        displayName: 'DOT/USD',
        pipLocation: -3,
        displayPrecision: 3,
        tradeUnitsPrecision: 2,
        minimumTradeSize: '0.1',
        maximumTrailingStopDistance: '100000',
        minimumTrailingStopDistance: '1',
        maximumPositionSize: '1000',
        maximumOrderUnits: '1000',
        marginRate: '0.02',
        financing: { longRate: '0.02', shortRate: '0.02', financingDaysOfWeek: [] }
    },
    {
        name: 'CRYPTO_MATIC_USD',
        type: 'CRYPTO',
        displayName: 'POL/USD',
        pipLocation: -4,
        displayPrecision: 4,
        tradeUnitsPrecision: 1,
        minimumTradeSize: '1',
        maximumTrailingStopDistance: '100000',
        minimumTrailingStopDistance: '1',
        maximumPositionSize: '1000',
        maximumOrderUnits: '1000',
        marginRate: '0.02',
        financing: { longRate: '0.02', shortRate: '0.02', financingDaysOfWeek: [] }
    }
]
